name: Remove ♻️
run-name: Remove
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Choose the branch to use.'
        default: 'develop'
        type: string
        required: true
      ACCOUNT:
        description: 'Choose account to remove from'
        default: 'sp-dev'
        type: choice
        options:
          - sp-dev
          - sp-stg
          - sp-prd
      STACK_PREFIX:
        description: 'Specify the stack prefix (if personal stack). Example: stack prefix of mz will result in tokeniser-api-cdk-sp-dev-mz-shared'
        type: string
      STACK:
        description: 'Choose the stack to remove'
        type: choice
        options:
            - dashboard
            - ecs
            - redis
            - rds
            - s3upload
            - shared
      DNS_REMOVAL:
        description: 'Flag to remove DNS records'
        type: boolean
        default: false
      CR_NUMBER:
        description: 'If it is a prod deployment and you have a CR, specify it here'
        type: string

defaults:
  run:
    shell: bash

env:
  CONFIG: tokeniser.env

jobs:
  pre-remove:
    name: pre-remove
    runs-on: [ fargate, '${{ inputs.ACCOUNT }}-general-x64-master' ]
    outputs:
      stack_prefix_lc: ${{ steps.stack-prefix.outputs.STACK_PREFIX_LC }}
      job_name: ${{ steps.job-name.outputs.JOB_NAME }}

    steps:
      - name: Job Summery
        run: |
          {
          echo "| Name | Value |"
          echo "| -------------- | ----------------- |"
          echo "ACCOUNT: ${{ inputs.ACCOUNT }}"
          echo "STACK_PREFIX: ${{ inputs.STACK_PREFIX }}"
          echo "STACK: ${{ inputs.STACK }}"
          echo "DNS_REMOVAL: ${{ inputs.DNS_REMOVAL }}"
          echo "CR_NUMBER: ${{ inputs.CR_NUMBER }}"
          } >> $GITHUB_STEP_SUMMARY

      - if: ${{ inputs.STACK_PREFIX != '' }}
        name: Ensure STACK_PREFIX is lower case
        id: stack-prefix
        run: |
          sp=${{ inputs.STACK_PREFIX }}
          echo "STACK_PREFIX_LC=${sp,,}" >> $GITHUB_OUTPUT


      - name: Validate CR Number
        if: contains('sp-prd', inputs.ACCOUNT)
        run: |
          if [[ -z '${{ inputs.CR_NUMBER }}' ]]; then
          echo "CR Number is required for production deployment. Terminating workflow."
          exit 1
          else 
          echo "CR Number: ${{ inputs.CR_NUMBER }}. Continuing with production deployment."
          fi

      - name: Create Job Name
        id: job-name
        run: |
          echo "JOB_NAME=${{ (inputs.STACK_PREFIX != '') && format('{0}-{1}-{2}', inputs.ACCOUNT, steps.stack-prefix.outputs.STACK_PREFIX_LC, inputs.STACK) || format('{0}-{1}', inputs.ACCOUNT, inputs.STACK) }}" >> $GITHUB_OUTPUT

  remove:
    name: remove-${{ needs.pre-remove.outputs.job_name }}
    runs-on: [fargate, '${{ inputs.ACCOUNT }}-general-x64-master']
    environment: ${{ inputs.ACCOUNT }}
    needs: pre-remove

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read ENV Config
        run: cat .github/workflows/${{ env.CONFIG }} >> $GITHUB_ENV

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

#      - name: Setup Yarn
#        working-directory: ./aws-infra/cdk
#        run: yarn

      - name: Print Versions
        run: |
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"
          echo "yarn: $(yarn -v)"

      - name: Set Stack Parameters
        if: always()
        run: |
            echo "stackName=${{ (inputs.STACK_PREFIX != '') && format('{0}-{1}', needs.pre-remove.outputs.stack_prefix_lc, inputs.STACK) || inputs.STACK }}" >> $GITHUB_ENV
            echo "stackPrefixCdkContext=${{ (inputs.STACK_PREFIX != '') && format('-c stackPrefix={0}', needs.pre-remove.outputs.stack_prefix_lc) || '' }}" >> $GITHUB_ENV

      - name: Print Stack Parameters
        if: always()
        run: |
          echo "stackName: ${{ env.stackName }}"
          echo "stackPrefixCdkContext: ${{ env.stackPrefixCdkContext }}"
