name: Test Actions
on: push

jobs:
  test-workflows:
    runs-on: ubuntu-latest
    steps:
      - run: |
          dddd2="github_merge_test_dka"
          if [[ "github_merge_test_dka" == github_merge_test_dka* ]]; then
            echo ":x: Artifact not uploaded to stg as it is not a release branch"
          fi
          echo "::notice Data wewe" >> $GITHUB_STEP_SUMMARY
        
