name: Chron Actions

env:
    CRON_JOB1: '11 00 * * 1-5'
    CRON_JOB2: '15 00 * * 1-5'
  
on:
   schedule:
     - cron: '10 03 * * 1-5'
     - cron: '15 03 * * 1-5'
     - cron: '35 23 * * 1-5'
     - cron: '10 04 * * 1-5'
     - cron: '10 03 * * 1-5'
      
jobs:
    job1:
        runs-on: ubuntu-latest
        name: Job 1

        steps:
            - run: |
                export TZ=Australia/Sydney
                echo "Current Run: ${{github.event.schedule }}"
                echo "Time Now: $(date '+%Y-%m-%d %H:%M:%S'"
                if [[ -z '${{ github.event.schedule == env.CRON_JOB1 }}' ]]; then
                    echo "Run at 1: ${{ env.CRON_JOB1 }}"
                elif  [[ -z '${{ github.event.schedule == env.CRON_JOB2 }}' ]]; then
                    echo "Run at 2: ${{ env.CRON_JOB2 }}"
                fi
       
      
