name: Matrix Workflow

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
         echo "matrix={\"include\": [{\"name\": \"ABC\", \"age\": \"20\"}, {\"name\": \"PQR\", \"age\": \"50\"}]}" >> "$GITHUB_OUTPUT"

  test:
    needs: build
    environment: sp-prd
    strategy:
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "name  -> ${{ matrix.name }}, age -> ${{ matrix.age }}"
