name: Chron Actions

env:
    CRON_JOB1: '58 11 * * 1-5'
    CRON_JOB2: '05 12 * * 1-5'
  
on:
   schedule:
        - cron: '58 11 * * 1-5'
        - cron: '05 12 * * 1-5'
      
jobs:
    job1:
        runs-on: ubuntu-latest
        name: Job 1

        steps:
            - run: |
                echo "Current Run: ${{github.event.schedule }}"
                if [[ -z '${{ github.event.schedule == env.CRON_JOB1 }}' ]]; then
                    echo "Run at 1: ${{ env.CRON_JOB1 }}"
                elif  [[ -z '${{ github.event.schedule == env.CRON_JOB2 }}' ]]; then
                    echo "Run at 2: ${{ env.CRON_JOB2 }}"
                fi
       
      
