name: Test Actions
on: push

env:
  STACK_PREFIX: 'dka'
  STACK: 'ecs'
  ECS_DEPLOYMENT: 'blue'
  STACK_PROFILE: 'default'
  ACCOUNT: 'sp-dev'
  DOCKER_TAG: '123456789-docker'
  
jobs:
  test-workflows:
    runs-on: ubuntu-latest
    steps:
      - run: |
          dddd2="github_merge_test_dka"
          if [[ "github_merge_test_dka" == github_merge_test_dka* ]]; then
            echo ":x: Artifact not uploaded to stg as it is not a release branch"
          fi
          echo "::notice:: Data wewweweww rgthtwe"
          echo "::debug::Set the Octocat variable"
          echo "::warning file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
          echo "::error file=app.js,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon"
          echo "::workflow-command parameter1={data},parameter2={data}::{command value}"

           stackPrefixLowerCase=${{ env.STACK_PREFIX,, }}
            stackPrefix=$([ stackPrefixLowerCase != "" ] && echo "${{ stackPrefixLowerCase }}-" || echo "")
            stackName=$([ env.STACK == "ecs" || env.STACK == "dashboard ] && echo " ${{ env.STACK }}-${{ env.ECS_DEPLOYMENT} }" || echo "${{ env.STACK }}")
            echo "stackName=${stackPrefix}${stackName}"  >> $GITHUB_ENV
            stackPrefixCdk=$([ stackPrefixLowerCase != "" ] && echo "-c stackPrefix=${{  stackPrefixLowerCase }} " || echo "")
            stackPrefixCdkContext="-c stackProfile=${{ env.STACK_PROFILE }} -c dockerimagetag=${{ env.DOCKER_IMAGE_TAG }} -c ecscolour=${{ env.ECS_DEPLOYMENT }} -c ecslive=${{ env.ECS_LIVE_STACK }}"
            echo "stackPrefixCdkContext=${stackPrefixCdk}${stackPrefixCdkContext}"  >> $GITHUB_ENV
            echo "exclusive=${{ (env.DEPLOY_EXCLUSIVE) && '--exclusively' || '' }}" >> $GITHUB_ENV
            echo "force=${{ (env.SKIP_CDK_DIFF) && '--force' || '' }}" >> $GITHUB_ENV
            
      - run: |
          echo "yarn cdk diff --fail tokeniser-api-cdk-${{ env.ACCOUNT }}-${{ env.stackName }} ${{ env.stackPrefixCdkContext }} ${{ env.scalingProfile }} -c dockerTag=${{ env.DOCKER_TAG }} ${{ env.exclusive }}"
        
