name: Delete old workflow runs
on: [push]
  #schedule:
  #  - cron: '45 02 * * *'
# Run monthly, at 00:00 on the 1st day of month.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        run: | 
           all_work_flows="$(gh run list --jq ' .[]| select(.createdAt > (now-( 30 * 86400) | strftime("%Y-%m-%dT%H-%M-%SZ") ))' --json name,number,databaseId,createdAt --repo github.com/dimuthu-abeynayakage-sportsbet/github-workflow --limit 1)"
           for row in $(echo "${all_work_flows}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            name=$(_jq '.name')
            echo "name: ${name}"
           done
        env:
         GH_TOKEN: ${{ inputs.gh_token }}

