name: Delete old workflow runs
on: [push]
  #schedule:
  #  - cron: '45 02 * * *'
# Run monthly, at 00:00 on the 1st day of month.

jobs:
  cleanup-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Retaining Day Onwords
        run: |
          retenctionDays=30
          retenctionDate=$(date '+%Y-%m-%d' -d "${retenctionDays} day ago")
          echo "retenctionDate=$retenctionDate" >> $GITHUB_ENV
        env:
         GH_TOKEN: ${{ github.token }}
         
      - name: Delete workflow runs
        run: | 
          echo "Date retenctionDate: ${{ env.retenctionDate }}"
          hasMore=true
          while [ $hasMore == true ]
          do
            obsolete_work_flows=$(gh run list --json name,number,databaseId,createdAt --repo github.com/dimuthu-abeynayakage-sportsbet/github-workflow --limit 5 | jq ' [.[]| select(.createdAt < env.retenctionDate)]' )
             OPEN_PULL_REQUESTS="$all_work_flows"
             for row in $(echo "${OPEN_PULL_REQUESTS}" | jq -r '.[] | @base64'); do
                _jq() {
                  echo ${row} | base64 --decode | jq -r ${1}
                }
                name=$(_jq '.name')
                number=$(_jq '.number')
                databaseId=$(_jq '.databaseId')
                createdAt=$(_jq '.createdAt')
                echo "Name: $name, number: $number, databaseId: $databaseId, createdAt: $createdAt"
             done
             echo "Queried Date: ($OPEN_PULL_REQUESTS)"
             if [ $obsolete_work_flows == ""]; then 
               hasMore=false
             fi
           done
           
        env:
         GH_TOKEN: ${{ github.token }}

