name: Delete old workflow runs
on: [push]
  #schedule:
  #  - cron: '45 02 * * *'
# Run monthly, at 00:00 on the 1st day of month.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Retaining Day Onwords
        run: |
          retenctionDate="2024-06-07"
          echo "retenctionDateNew=$retenctionDate" >> $GITHUB_ENV
      - name: Delete workflow runs
        run: | 
          echo "Date retenctionDateNew: ${{ env.retenctionDateNew }}"
          all_work_flows=$(gh run list --json name,number,databaseId,createdAt --repo github.com/dimuthu-abeynayakage-sportsbet/github-workflow --limit 5 | jq ' .[]| select(.createdAt > env.retenctionDateNew)' )
           echo "Data: ${all_work_flows}"
           OPEN_PULL_REQUESTS=$all_work_flows
           for row in $(echo "${OPEN_PULL_REQUESTS}" | jq -r '.[] | @base64'); do
              _jq() {
                echo ${row} | base64 --decode | jq -r ${1}
              }
              name=$(_jq '.name')
              echo "Name: ${name}"
           done
           
        env:
         GH_TOKEN: ${{ github.token }}

